# Generated by Django 4.2.7 on 2023-11-12 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Carrera', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_profesores', models.TextField()),
                ('Apellido_profesores', models.TextField()),
                ('Correo_profesores', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_estudiante', models.TextField()),
                ('Apellido_estudiante', models.TextField()),
                ('Edad_estudiante', models.IntegerField()),
                ('Carrera_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDeDatos.carreras')),
            ],
        ),
        migrations.CreateModel(
            name='Asignaturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_asignatura', models.TextField()),
                ('Carrera_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDeDatos.carreras')),
                ('Profesor_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseDeDatos.profesores')),
            ],
        ),
    ]
