# Generated by Django 4.2.6 on 2023-11-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDeDatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaturas',
            name='Nombre_asignatura',
            field=models.CharField(verbose_name=200),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='Apellido_estudiante',
            field=models.CharField(verbose_name=200),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='Edad_estudiante',
            field=models.CharField(verbose_name=200),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='Nombre_estudiante',
            field=models.CharField(verbose_name=200),
        ),
        migrations.AlterField(
            model_name='profesores',
            name='Apellido_profesores',
            field=models.CharField(verbose_name=200),
        ),
        migrations.AlterField(
            model_name='profesores',
            name='Correo_profesores',
            field=models.CharField(verbose_name=200),
        ),
        migrations.AlterField(
            model_name='profesores',
            name='Nombre_profesores',
            field=models.CharField(verbose_name=200),
        ),
    ]
